version: '3'
services:
  web:
    image: CA4:1.0
    ports:
      - "80:80"
    volumes:
      - ./web:/app
  database:
    image: CA4:2.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
