version: '3'
services:
  web:
    image: commitcrew/webserver:latest
    links:
      - database
    ports:
      - "80:80"
  database:
    image: commitcrew/mysql:latest
    ports: 
    - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root