version: '3'
services:
  web:
    image: commitcrew/webserver:latest
    ports:
      - "80:80"
    networks:
      - my_network
  database:
    image: commitcrew/my_sql:latest  # Corrected image name
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "studentInfo"
    networks:
      - my_network

networks:
  my_network:
