version: '3'
services:
  web:
    image: CA4:1.0
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=database_connection_string
    volumes:
      - ./web:/app
  database:
    image: CA4:2.0
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database_name
    volumes:
      - ./db:/var/lib/mysql
