version: '3'
services:
  web:
    image: webapp:latest
    ports:
      - "80:80"
    volumes:
      - ./web:/app
  database:
    image: firstsql_image:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql